Repository HealthPlatformMadeEasy/HealthPlatformApp, pull requests merged in 2023-06, with the labels that each got.

#6 test bug
  doc/demo/#1DEMO.md
Labels: bug

#8 Update README.md
  README.md
Labels: documentation

#9 Revert "Add postgres db connection"
  Server/pom.xml
  Server/src/main/java/com/api/server/controller/HelpController.java
  Server/src/main/java/com/api/server/entities/AppUser.java
  Server/src/main/java/com/api/server/mappers/UserMapper.java
  Server/src/main/java/com/api/server/model/UserDTO.java
  Server/src/main/java/com/api/server/repositories/UserRepository.java
  Server/src/main/java/com/api/server/services/UserService.java
  Server/src/main/java/com/api/server/services/UserServiceImpl.java
  Server/src/main/resources/application-localpostgres.properties
  Server/src/main/resources/application.properties
  Server/src/main/resources/database/migrations/V1__init-postgres-database.sql
  Server/src/main/resources/database/migrations/calories.csv
  Server/src/main/resources/import.sql
Labels: enhancement

#24 23-calories-calculator-entity-mapping-service-creation
  Server/src/main/java/com/api/server/controller/FoodProductController.java
  Server/src/main/java/com/api/server/controller/HelpController.java
  Server/src/main/java/com/api/server/controller/UserController.java
  Server/src/main/java/com/api/server/entities/AppUser.java
  Server/src/main/java/com/api/server/mappers/FoodProductMapper.java
  Server/src/main/java/com/api/server/mappers/UserMapper.java
  Server/src/main/java/com/api/server/model/CaloricCalculationRequest.java
  Server/src/main/java/com/api/server/model/CaloricResponse.java
  Server/src/main/java/com/api/server/model/FoodProductResponse.java
  Server/src/main/java/com/api/server/model/UserDTO.java
  Server/src/main/java/com/api/server/repositories/FoodProductRepository.java
  Server/src/main/java/com/api/server/repositories/UserRepository.java
  Server/src/main/java/com/api/server/services/FoodProductService.java
  Server/src/main/java/com/api/server/services/FoodProductServiceImpl.java
  Server/src/main/java/com/api/server/services/UserServiceImpl.java
  Server/src/main/resources/application.properties
  Server/src/main/resources/import.sql
Labels: enhancement

#26 25-test
  README.md
Labels: invalid

#35 33-setup-db-enviroments
  Server/src/main/resources/application-development.properties
  Server/src/main/resources/application-production.properties
  Server/src/main/resources/application.properties
Labels: enhancement

#36 21-seed-database-with-food-info-from-csv-file
  Server/pom.xml
  Server/src/main/java/com/api/server/ServerApplication.java
  Server/src/main/java/com/api/server/entities/FoodProduct.java
  Server/src/main/java/com/api/server/repositories/FoodProductRepository.java
  Server/src/main/java/com/api/server/services/DatabaseSeedService.java
  Server/src/main/java/com/api/server/services/FoodProductServiceImpl.java
  Server/src/main/java/com/api/server/utils/CsvUtils.java
  Server/src/main/java/com/api/server/utils/StringToLongDeserializer.java
  Server/src/main/resources/database/seed/calories.csv
  Server/src/main/resources/import.sql
Labels: enhancement

#37 34-fix-food-product-entity
  Server/src/main/java/com/api/server/entities/AppUser.java
  Server/src/main/java/com/api/server/entities/FoodProduct.java
  Server/src/main/resources/import.sql
Labels: enhancement

#38 30-food-product-model-validation
  Server/pom.xml
  Server/src/main/java/com/api/server/controller/FoodProductController.java
  Server/src/main/java/com/api/server/entities/FoodProduct.java
  Server/src/main/java/com/api/server/model/contracts/UserDTO.java
  Server/src/main/java/com/api/server/model/request/CaloricCalculationRequest.java
  Server/src/main/java/com/api/server/model/response/CaloricResponse.java
  Server/src/main/java/com/api/server/model/response/FoodProductResponse.java
  Server/src/main/java/com/api/server/services/FoodProductServiceImpl.java
  Server/src/main/resources/application-development.properties
Labels: enhancement
